services:
  migrate:
    build:
      context: .
      target: migrator
    env_file:
      - .env
    restart: "no"

  app:
    build:
      context: .
      target: runner
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped
